# Generated by Django 4.2.23 on 2025-08-18 15:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sku_producto', models.CharField(db_index=True, max_length=20, unique=True)),
                ('nombre_producto', models.CharField(db_index=True, max_length=100)),
                ('precio_producto_mxn', models.DecimalField(decimal_places=2, max_digits=6)),
                ('marca', models.CharField(blank=True, max_length=100, null=True)),
                ('creado_fecha', models.DateTimeField(auto_now_add=True)),
                ('modificado_fecha', models.DateTimeField(auto_now=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_creados', to=settings.AUTH_USER_MODEL)),
                ('modificado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos_modificados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
